#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;


layout(binding=5, std140) readonly buffer Counters {
	uint shadowCounter;
	uint reflrectionCounter;
};

layout(binding=6, std430) writeonly buffer DispatchIndirect {
	uvec4 dispatchIndirect[];
};

//Handling intersection

void main() {
	dispatchIndirect[0] = uvec4(uint(ceil(float(shadowCounter) / 64)), 1, 1, 1);
	dispatchIndirect[1] = uvec4(uint(ceil(float(reflrectionCounter) / 64)), 1, 1, 1);
}