#version 450
#extension GL_GOOGLE_include_directive : require
#include "defines.glsl"
#include "rand_util.glsl"

layout(binding=0, std140) buffer SeedBuffer {
	Seed seed;
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
	vec2 off = rand(vec2(seed.cpuOffsetX, seed.cpuOffsetY) + seed.sampleCount);
	seed.randomX = off.x;
	seed.randomY = off.y;
	++seed.sampleCount;
}